// VKE regular video downloader — v27
// One-click exact 720p; no hover quality picker and no preview capture as first choice.
(function(){
'use strict';
if(window.__vkeVideoDownloader27)return;window.__vkeVideoDownloader27=true;
const STYLE=`
.vke-video-dl-wrap{display:inline-flex!important;position:relative!important;align-items:center!important;justify-content:center!important;flex:0 0 auto!important;margin:0 4px!important;height:36px!important;z-index:80!important}
.vke-video-dl-btn{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:36px!important;min-width:42px!important;padding:0 10px!important;border:0!important;border-radius:10px!important;background:transparent!important;color:var(--vkui--color_text_secondary,#818c99)!important;cursor:pointer!important;outline:none!important;box-sizing:border-box!important}
.vke-video-dl-wrap:hover{z-index:2147483646!important}.vke-video-dl-btn:hover{background:var(--vkui--color_background_secondary_alpha,rgba(0,0,0,.08))!important;color:var(--vkui--color_text_primary,#000)!important}.vke-video-dl-btn[disabled]{pointer-events:none!important;opacity:.78!important}
.vke-video-dl-btn svg{width:24px!important;height:24px!important;fill:currentColor!important;pointer-events:none!important}
.vke-video-dl-ring{width:28px!important;height:28px!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:conic-gradient(currentColor calc(var(--p,0)*1%),rgba(127,127,127,.22) 0)!important;position:relative!important}.vke-video-dl-ring:after{content:'';position:absolute;inset:3px;border-radius:50%;background:var(--vkui--color_background_content,#fff)!important}.vke-video-dl-ring>span{position:relative;z-index:1;font:700 8px/1 -apple-system,BlinkMacSystemFont,Roboto,sans-serif!important}
.vke-video-dl-spin{width:22px!important;height:22px!important;border:3px solid rgba(127,127,127,.25)!important;border-top-color:currentColor!important;border-radius:50%!important;animation:vke-video-dl-spin .7s linear infinite!important}@keyframes vke-video-dl-spin{to{transform:rotate(360deg)}}
.vke-video-dl-toast{position:fixed!important;left:50%!important;bottom:24px!important;transform:translateX(-50%)!important;z-index:2147483647!important;padding:9px 14px!important;border-radius:10px!important;background:rgba(32,34,37,.96)!important;color:#fff!important;font:13px/18px -apple-system,BlinkMacSystemFont,Roboto,sans-serif!important}
`;
const ICON=`<svg viewBox="0 0 28 28" aria-hidden="true"><path d="M14 18c-.3 0-.6-.1-.8-.3l-5-5a1.06 1.06 0 0 1 1.5-1.5l3.2 3.2V6a1.1 1.1 0 0 1 2.2 0v8.4l3.2-3.2a1.06 1.06 0 0 1 1.5 1.5l-5 5c-.2.2-.5.3-.8.3Z"/><path d="M22 22H6a1 1 0 1 1 0-2h16a1 1 0 1 1 0 2Z"/></svg>`;
if(!document.getElementById('vke-video-dl-style-v27')){const s=document.createElement('style');s.id='vke-video-dl-style-v27';s.textContent=STYLE;document.head.appendChild(s)}
let btn=null,wrap=null,seq=0,stopPoll=null,attachTimer=0;
function toast(text){let x=document.querySelector('.vke-video-dl-toast');if(!x){x=document.createElement('div');x.className='vke-video-dl-toast';document.body.appendChild(x)}x.textContent=text;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2200)}
function visible(el){if(!el)return false;const r=el.getBoundingClientRect?.();if(!r||r.width<2||r.height<2)return false;const c=getComputedStyle(el);return c.display!=='none'&&c.visibility!=='hidden'&&Number(c.opacity||1)>0}
function isClip(){return /(?:^|\/)(?:clips?|clip)-?\d+_/i.test(location.pathname)||/[?#&]z=clip-?/i.test(location.href)||!!document.querySelector('[data-testid="clips-controls-like-button"],[data-testid="clips-controls-more-actions-button"]')}
function isStory(){return !!document.querySelector('button[data-testid="stories_viewer_menu_icon"],[data-testid="stories_viewer"]')}
function getId(){return new Promise(resolve=>{const id=`v27_${Date.now()}_${++seq}`;let done=false;const on=e=>{if(e.source!==window||e.data?.type!=='CLP_ACTIVE_ID_RESULT'||e.data.clientId!==id)return;done=true;window.removeEventListener('message',on);resolve(e.data.id||null)};window.addEventListener('message',on);window.postMessage({type:'CLP_GET_ACTIVE_ID',clientId:id},'*');setTimeout(()=>{if(done)return;window.removeEventListener('message',on);resolve(null)},2500)})}
function getData(id){return new Promise((resolve,reject)=>{const clientId=`vd27_${Date.now()}_${++seq}`;let done=false;const on=e=>{if(e.source!==window)return;const d=e.data||{};if(d.type==='CLP_VIDEO_DATA_RESPONSE'&&d.clientId===clientId){done=true;window.removeEventListener('message',on);clearTimeout(timer);resolve(d.vsrc||null)}else if(d.type==='CLP_VIDEO_ERROR'&&d.clientId===clientId){done=true;window.removeEventListener('message',on);clearTimeout(timer);reject(new Error(d.error||'VK не отдал ссылку'))}};window.addEventListener('message',on);window.postMessage({type:'CLP_REQUEST_VIDEO_URL',clientId,clipId:id||null},'*');const timer=setTimeout(()=>{if(done)return;window.removeEventListener('message',on);reject(new Error('Таймаут получения ссылки'))},16000)})}
function pick720(vsrc){if(!vsrc)return null;for(const q of ['720p','mp4_720','url720','720'])if(typeof vsrc[q]==='string'&&/^https?:\/\//i.test(vsrc[q])&&/\.mp4(?:[?#]|$)/i.test(vsrc[q])&&!/\/recoding\/|\/preview(?:[/?]|$)|getVideoPreview/i.test(vsrc[q]))return {q:'720p',url:vsrc[q]};for(const q of ['1080p','480p','360p','240p','144p'])if(typeof vsrc[q]==='string'&&/^https?:\/\//i.test(vsrc[q])&&/\.mp4(?:[?#]|$)/i.test(vsrc[q])&&!/\/recoding\/|\/preview(?:[/?]|$)|getVideoPreview/i.test(vsrc[q]))return {q:q,url:vsrc[q]};return null}
function activeVideo(){const vids=[...document.querySelectorAll('video')].filter(visible);if(!vids.length)return null;const playing=vids.filter(v=>!v.paused&&!v.ended&&(v.currentSrc||v.src));const pool=playing.length?playing:vids;pool.sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return br.width*br.height-ar.width*ar.height});return pool[0]||null}
function setVisual(mode,p=0){if(!btn)return;if(mode==='wait'){btn.disabled=true;btn.innerHTML='<span class="vke-video-dl-spin"></span>';return}btn.disabled=true;btn.innerHTML=`<span class="vke-video-dl-ring" style="--p:${Math.max(0,Math.min(100,p))}"><span>${p?Math.round(p)+'%':'…'}</span></span>`}
function reset(){if(btn){btn.disabled=false;btn.innerHTML=ICON}}
function start(id,label){stopPoll?.();setVisual('progress',0);stopPoll=window.__vkePollDownload?.(id,d=>{const p=d.totalBytes>0?d.bytesReceived/d.totalBytes*100:0;setVisual('progress',p)},d=>{const ok=d.state==='complete';setVisual('progress',ok?100:0);toast(ok?`${label}: готово`:`${label}: ошибка`);setTimeout(reset,700);stopPoll=null})}
async function direct(url,id,label){const r=await chrome.runtime.sendMessage({type:'VKE_DIRECT_DOWNLOAD',url,filename:`vk_video_${String(id||Date.now()).replace(/^-/, 'm')}_${label.replace(/[^0-9A-Za-zА-Яа-я_-]/g,'')}.mp4`});if(!r?.ok)throw new Error(r?.error||'Не удалось начать скачивание');start(r.downloadId,label)}
async function download(){if(!btn||btn._busy)return;btn._busy=true;setVisual('wait');try{const id=await getId();let data=null;try{data=await getData(id)}catch{await new Promise(r=>setTimeout(r,700));data=await getData(id).catch(()=>null)}const picked=pick720(data);if(picked){await direct(picked.url,id,picked.q);return}const v=activeVideo();const src=v?.currentSrc||v?.src||'';if(/^https?:\/\//i.test(src)&&/\.mp4(?:[?#]|$)/i.test(src)&&!/\/preview(?:[/?]|$)|getVideoPreview|\/recoding\//i.test(src)){await direct(src,id,'source');return}throw new Error('Не удалось получить полную ссылку на видео') }catch(e){toast(e?.message||'Не удалось скачать видео');btn._busy=false;reset()}}
function findAnchor(){const selectors=['[data-testid="video_modal_like_button"]','[data-testid="video_page_like_button"]','[data-testid="video_modal_more_button"]','[data-testid="video_page_more_button"]','[data-testid*="video-controls" i] button','[data-testid*="player" i] button','button[aria-label*="Подробнее" i]','button[aria-label*="More" i]','button[aria-label*="Поделиться" i]'];for(const s of selectors){const x=[...document.querySelectorAll(s)].find(visible);if(x)return x}return null}
function attach(){if(isClip()||isStory())return;if(wrap&&document.body.contains(wrap))return;const anchor=findAnchor();const v=activeVideo();if(!anchor&&!v)return;wrap=document.createElement('div');wrap.className='vke-video-dl-wrap';wrap.dataset.vkeVideoDownload='1';btn=document.createElement('button');btn.type='button';btn.className='vke-video-dl-btn';btn.title='Скачать видео 720p';btn.setAttribute('aria-label','Скачать видео 720p');btn.innerHTML=ICON;wrap.appendChild(btn);btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();download()});if(anchor?.parentElement){anchor.parentElement.insertBefore(wrap,anchor)}else if(v){let p=v.parentElement;for(let i=0;p&&i<8;i++,p=p.parentElement){const r=p.getBoundingClientRect?.();if(r&&r.width>250&&r.height>180){if(getComputedStyle(p).position==='static')p.style.position='relative';wrap.style.position='absolute';wrap.style.right='12px';wrap.style.top='12px';wrap.style.height='44px';p.appendChild(wrap);break}}}}
new MutationObserver(()=>{clearTimeout(attachTimer);attachTimer=setTimeout(()=>{if(wrap&&!document.body.contains(wrap)){wrap=null;btn=null}attach()},180)}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['href','data-video-id','data-clip-id']});
[300,800,1500,2500,4000].forEach(ms=>setTimeout(attach,ms));setInterval(attach,1200);
})();
